site_name: Anderson Lab @ UC Berkeley
site_url: https://UCB-BioE-Anderson-Lab.github.io/

theme:
  name: material
  logo: images/logo.png
  icon:
    repo: null
  features:
    - content.code.annotate
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Home: index.md
  - Publications: publications.md
  - Teaching: teaching.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji

plugins:
  - search

extra_css:
  - css/custom.css

extra:
  page:
    '*':
      hide:
        - navigation
        - toc
        - footer
  social: []
  generator: false
  copyright: '© 2025 University of California, Berkeley'
extra_javascript: []
extra_templates: []